### PR TITLE
remove initialize_db_var

### PR DESCRIPTION
**Pull request by biggerbraintime**
its very unnecessary

### CODE REVIEW

**Comment by arceuss** [comment]
BAD PR THE CODE ISNT SHIT

**Comment by biggerbraintime** [comment]
> BAD PR THE CODE ISNT SHIT

im removing something that makes the code look like spaghetti

**Comment by arceuss** [comment]
> 
> 
> > BAD PR THE CODE ISNT SHIT
> 
> im removing something that makes the code look like spaghetti

instantly gets closed

**Comment by biggerbraintime** [comment]
> > > BAD PR THE CODE ISNT SHIT
> > 
> > 
> > im removing something that makes the code look like spaghetti
> 
> instantly gets closed

he can close it if he wants his code to look like horrible spaghetti

**Comment by chaziz94** [comment]
> 
> 
> BAD PR THE CODE ISNT SHIT

says the guy whose fursona doesn't even have a nose lmfao

**Review by chaziz94 — APPROVED** [review]
And now the world is saved from the apocalypse.

**Review by forkiesassds — APPROVED** [review]

**Comment by biggerbraintime** [comment]
im closing this pr due to the amount of conflicts

**Pull request closed without merging**
