### PR TITLE
Add anchors to thumbnails and profile pictures

### PR DESCRIPTION
**Pull request by Nightlinbit**

### CODE REVIEW

**Comment by biggerbraintime** [comment]
i think my man forgot how to indent properly

**Comment by the-real-sumsome** [comment]
can you please fix the indents

**Comment by Nightlinbit** [comment]
Indentation should be fine in any code editor; apparently Github screws up with mixed tab/space indenting. Even pulling this code and opening it in Notepad++ displays as it should.

**Comment by Nightlinbit** [comment]
Indentations are fixed now.

**Pull request merged**
